### ISSUE TITLE
Links to other emmet project look weird on cheat sheet

### ISSUE THREAD

**Issue by Fahrradflucht** [emmetio/web#3]
There seems to be something wrong with the recent change that adds the links to the other emmet project. They look right in the normal docs view, but on the [cheat sheet](http://docs.emmet.io/cheat-sheet/) they are jammed to the top.

![screenshot 2016-02-19 15 44 17](https://cloud.githubusercontent.com/assets/13237661/13178589/f61ee6ee-d71f-11e5-8d5d-81dce004e92e.png)

**Comment by sergeche** [comment]
Yikes! You’re right, just pushed update. Thank you!
